<nav>
<ul>
<li><a href="home.php"> home </a></li>
<li><a href="mail_list_signup.php"> mail sign up</a></li>
<li><a href="mail_list.php">mail list</a></li>
<li><a href="admin_loggin.php">Log In</a></li>
<li><a href="products.php">products</a></li>
<li><a href="my_cart.php">cart</a></li>
<li><a href="sessionEnd.php">log out</a></li>
<li><a href="register.php">register</a></li>
<li><a href="contact.php">contact us</a></li>
</ul>
</nav>